[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# Grundsicherheit f√ºr alles
[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"

# Google Ads / GA4 Attribution (nur HTML)
[[headers]]
for = "/*.html"
  [headers.values]
  Attribution-Reporting-Eligible = '{"trigger": "true"}'
  Attribution-Reporting-Support = '{"os": "true"}'

[[headers]]
for = "/kundenlogin/account"
  [headers.values]
  Basic-Auth = "tenwords tenwords2026"

[[headers]]
for = "/kundenlogin/account/"
  [headers.values]
  Basic-Auth = "tenwords tenwords2026"

[[headers]]
for = "/kundenlogin/account/songbook_2"
  [headers.values]
  Basic-Auth = "tenwords tenwords2026"

[[headers]]
for = "/kundenlogin/account/songbook_2/"
  [headers.values]
  Basic-Auth = "tenwords tenwords2026"

[[headers]]
for = "/kundenlogin/account/songbook_3"
  [headers.values]
  Basic-Auth = "tenwords tenwords2026"

[[headers]]
for = "/kundenlogin/account/songbook_3/"
  [headers.values]
  Basic-Auth = "tenwords tenwords2026"

[[headers]]
for = "/kundenlogin/account/songbook_4"
  [headers.values]
  Basic-Auth = "tenwords tenwords2026"

[[headers]]
for = "/kundenlogin/account/songbook_4/"
  [headers.values]
  Basic-Auth = "tenwords tenwords2026"